#!/bin/bash

echo "Give a bootnode name: "
read name
bootnode_dir=$(pwd)/$name

echo "Bootnone host (default localhost) : "
read host
if [ -z "$host" ]; then
    host="localhost"
fi

echo "Bootnode port (default 30300):"
read port
if [ -z "$port" ]; then
    port="30300"
fi

mkdir "$bootnode_dir"
createBootNode $bootnode_dir $host $port