#!/usr/bin/python3
import argparse, os
from tools import deployContract

try:

    parser = argparse.ArgumentParser(description='Deploy Smart Contract')
    parser.add_argument('path', type=str,
                        help='Path to smart contract')
    parser.add_argument('rpc', type=str, default="http://localhost:32301",
                        help='Blockchain network RPC')
    try:
        args = parser.parse_args()
    except:
        parser.print_help()
        exit(0)
    
    deployContract(args.rpc,args.path)

except Exception as e:
    raise e