#!/usr/bin/python3
import argparse, os, json
from web3 import Web3
from web3.middleware import geth_poa_middleware
from tools import deployContract, sendEth

contracts = [
     "faucet",
]

try:
    script_path = os.path.dirname(os.path.abspath(__file__))

    parser = argparse.ArgumentParser(description='Deploy Smart Contract')
    parser.add_argument('path', type=str, default="{script_path}/../contracts",
                        help='Path to folder with all the contracts')
    parser.add_argument('icp', type=str, default=f"./geth.icp",
                        help='Path to ICP file of a running network peer')
    try:
        args = parser.parse_args()
    except:
        parser.print_help()
        exit(0)

    if ( not os.path.exists(args.icp) ):
            print("Please provide a valid geth.icp file or run the script in a folder with a geth.icp file")
            print("Make sure the account you are connecting to has some gas")
            exit(0)
    if ( not os.path.exists(args.path)):
         pass

    for contract in os.listdir(args.path):
        if contract[-4:] != ".sol": continue #Not a contract
        contractPath = os.path.join(args.path, contract)
        if os.path.exists(contractPath+".json"): continue #Contract Already Deployed
        if not os.path.isfile(contractPath): continue #Not a file
        contractName = contract[:-4]
        cotractAddress = deployContract(args.icp,contractPath)
        if contractName == "faucet":
                sendEth(args.icp,cotractAddress,100000000000000000000000000000000000000-500000000000000000000)

except Exception as e:
    raise e